apiVersion: triggers.tekton.dev/v1alpha1 
kind: TriggerTemplate 
metadata:
  name: github-trigger-template
  namespace: cicd-pipelines
spec:

  params: 
  - name: git-repo-url
    description: The git repository url
  - name: git-repo-name
    description: The name of the deployment to be created / patched
  - name: git-revision
    description: The git revision

  resourcetemplates: 
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: build-deploy-$(tt.params.git-repo-name)-$(uid)
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: build-and-deploy
      params:
      - name: git-url
        value: $(tt.params.git-repo-url)
      - name: git-revision
        value: $(tt.params.git-revision)
      workspaces:
      - name: shared-workspace
        volumeClaimTemplate:
         spec:
          accessModes:
           - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi