kind: Subscription
apiVersion: operators.coreos.com/v1alpha1
metadata:
  name: rhsso-operator-subscription
spec:
  channel: alpha
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace 