apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: default-keycloakrealm
  labels:
    app: keycloak
    realm: default
spec:
  realm:
    realm: "default"
    enabled: True
    displayName: "Default Realm"
  instanceSelector:
    matchLabels:
      app: keycloak