apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: admin
  labels:
    app: keycloak
spec:
  user:
    username: "admin"
    firstName: "Admin"
    lastName: "Admin"
    email: "admin@keycloak.org"
    enabled: True
    credentials:
      - type: "password"
        value: "12345"
  realmSelector:
    matchLabels:
      realm: default